application: ai-class-2017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: .*
  script: app.main.app
  secure: always

libraries:
- name: jinja2
  version: latest

skip_files:
- ^.git.*$
- ^.idea.*$
- ^.sass-cache.*$
- ^node_modules.*$
- ^scripts.*$
- ^.*\.iml$
- ^.*\.pyc$